version: '3.8'

services:
  pactum-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pactum-api
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3333
      - APP_KEY=${APP_KEY}
      - DRIVE_DISK=local
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    command: ['npm', 'run', 'start']
